name: React Native CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Remove node_modules and lock file
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies with force
        run: npm install --force

      - name: Install jest-environment-jsdom
        run: npm install --save-dev jest-environment-jsdom

      - name: Run tests
        run: npm test
