name: React Native CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Remove node_modules and lock file
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies with force
        run: npm install --force

      - name: Install jest-environment-jsdom
        run: npm install --save-dev jest-environment-jsdom --force

      - name: Install react-native-install-referrer with --legacy-peer-deps
        run: npm install react-native-install-referrer --legacy-peer-deps

      - name: Create __mocks__ directory
        run: mkdir -p __mocks__

      - name: Mock react-native-install-referrer
        run: |
          echo "module.exports = { getInstallReferrer: jest.fn().mockResolvedValue({ installReferrer: 'dummy_referrer', referrerTime: 123456789 }) };" > __mocks__/react-native-install-referrer.js

      # Build APK
      - name: Build Android Release APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      # Upload APK as artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
