name: Deploy Alex-user

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: "192.168.43.216"
        username: "root"
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p /var/www/html/alex-user
          cd /var/www/html/alex-user
          
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          if [ ! -d ".git" ]; then
            git clone git@github.com:rohyaditav/alex-user.git .
          else
            git remote set-url origin git@github.com:rohyaditav/alex-user.git
            git fetch origin master
            git reset --hard origin/master
          fi

          npm install
          # Optional if React Native app:
          # npm run build
          pm2 restart alex-user || pm2 start index.js --name alex-user
          pm2 save
          pm2 list
