name: React Native Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies with legacy peer deps
        run: |
          npm install --legacy-peer-deps

      - name: Fix 'compile' to 'implementation' in build.gradle for react-native-geocoder
        run: |
          if [ -f "node_modules/react-native-geocoder/android/build.gradle" ]; then
            sed -i 's|compile fileTree|implementation fileTree|' node_modules/react-native-geocoder/android/build.gradle
          else
            echo "File node_modules/react-native-geocoder/android/build.gradle not found. Skipping sed command."
          fi

      - name: Run build
        run: |
          npm run android  # Or 'npm run ios' depending on your target platform

      - name: Run tests
        run: |
          npm test
