name: React Native Build CI 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'  # Or '11' if your build requires it

      - name: Install dependencies with legacy peer deps
        run: |
          npm install --legacy-peer-deps

      - name: Fix Gradle config for react-native-geocoder
        run: |
          FILE="node_modules/react-native-geocoder/android/build.gradle"
          if [ -f "$FILE" ]; then
            echo "Patching $FILE"
            sed -i 's|^[ \t]*compile |    implementation |g' "$FILE"
            sed -i 's|implementationSdkVersion *( *[0-9]* *)|compileSdkVersion 33|g' "$FILE"
          else
            echo "$FILE not found, skipping patch."
          fi

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Run tests
        run: |
          npm test
