name: Android CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install
          
      - name: Downgrade Reanimated for RN 0.74.x
        run: |
          REANIMATED_VERSION=$(npm list react-native-reanimated | grep -oP '(?<=react-native-reanimated@)[\d.]+' || echo "none")
          RN_VERSION=$(node -p "require('./package.json').dependencies['react-native']")

          if [[ "$RN_VERSION" == "0.74.1" ]] && [[ "$REANIMATED_VERSION" != "3.7.1" ]]; then
            echo "Downgrading react-native-reanimated to 3.7.1 for RN 0.74.1..."
            npm install react-native-reanimated@3.7.1
          fi

      - name: Clean Gradle
        run: cd android && ./gradlew clean

      - name: Build Android App
        run: |
          cd android
          ./gradlew assembleDebug
